import * as THREE from "three";
import type { BrowserPacketV2, ComputeResult, FirstHitResult, PackingLevel, PackingMode, Quat, RigidGroup, SceneDocumentV2, Vec3 } from "./contracts";
import { EditHistory } from "../editor/history";
import { computeFirstHit } from "../firstHit/firstHit";
import { parseSceneV2, SceneValidationError, serializeSceneV2 } from "../importExport/sceneIo";
import { generateKou } from "../kou/generateKou";
import { generatePacking } from "../packing/generatePacking";
import { FrameMeter } from "../performance/benchmarks";
import { SceneLabViewport } from "../renderer/SceneLabViewport";
import { loadSceneV2, sceneCatalogue, defaultSceneV2Id } from "../scenes/catalogue";
import { computeBodyPairs, symplecticStep } from "../simulation/engine";
import { exactCapPolarGaussSphere, fixedFibonacciCurvedAngular, governedPlayback, V2B3C_GOLDEN, type AngularOperator } from "../simulation/curvedSolidAngle";
import { motionLedgers } from "../diagnostics/ledgers";
import { actionTallyVectors, parseActionTallyPlayback, vectorNorm, type ActionTallyBodyId, type ActionTallyBranchId, type ActionTallyPlayback } from "../diagnostics/actionTallyPlayback";
import { matchedVectorNorm, parseMatchedResidualPlayback, type MatchedResidualCaseId, type MatchedResidualPlayback } from "../diagnostics/matchedResidualPlayback";
import { PACKET_AUTHORITY_NOTICE, parseBrowserPacketV2 } from "../packets/authority";
import { computeDirect } from "../kernel";
import { loadBuiltInScene } from "../scenes";
import { initializeWebGpu } from "../webgpu";

const APP_COMMIT = import.meta.env.VITE_COMMIT_SHA || "LOCAL_UNPUBLISHED_BUILD";
const fmt = (value: number) => Number.isFinite(value) ? (Math.abs(value) > 1e4 || (Math.abs(value) < 1e-3 && value !== 0) ? value.toExponential(3) : value.toFixed(4)) : String(value);

const template = `
<main class="lab-shell v2">
 <header class="topbar"><div class="brand-lockup"><div class="brand-mark"><span></span><i></i></div><div><p class="eyebrow">PUBLIC INTERACTIVE PREVIEW</p><h1>VoxelLab Scene Lab <span>V2</span></h1></div></div><div class="topbar-meta"><span class="status-chip preview">PREVIEW · NOT AUTHORITY</span><span class="commit-chip">commit <code id="app-commit"></code></span><a href="https://github.com/svidetelsmysla-cmyk/voxellab-web" target="_blank">Repository ↗</a></div></header>
 <section class="workspace">
  <aside class="panel left-panel">
   <div class="panel-heading"><div><p class="eyebrow">SCENE AUTHORING</p><h2>Scene graph</h2></div><span id="object-count" class="count-pill"></span></div>
   <label class="field-label" for="scene-select">Scene suite S01–S17</label><select id="scene-select" data-testid="scene-select"></select>
   <p id="scene-description" class="scene-description"></p><p id="mobility-summary" class="claim-note"></p>
   <div class="compact-actions"><button id="add-body">ADD</button><button id="duplicate-body">DUPLICATE</button><button id="delete-body">DELETE</button><button id="group-body">GROUP</button><button id="ungroup-body">UNGROUP</button></div>
   <div id="scene-tree" class="scene-tree" data-testid="scene-tree"></div>
   <section class="inspector"><div class="section-rule"><span>SELECTED BODY</span></div><h3 id="selected-name">—</h3>
    <div class="compact-actions"><button id="lock-selected">LOCK</button><button id="unlock-selected">UNLOCK</button><button id="undo">UNDO</button><button id="redo">REDO</button></div>
    <div class="transform-toolbar"><button id="gizmo-translate">MOVE</button><button id="gizmo-rotate">ROTATE</button><select id="gizmo-space"><option>world</option><option>local</option></select><label>snap <input id="snap-position" type="number" value="0.1" step="0.05"></label></div>
    <div class="coordinate-grid" data-testid="transform-editor"><label>X<input id="pos-x" type="number" step="0.05"></label><label>Y<input id="pos-y" type="number" step="0.05"></label><label>Z<input id="pos-z" type="number" step="0.05"></label><label>RX°<input id="rot-x" type="number" step="5"></label><label>RY°<input id="rot-y" type="number" step="5"></label><label>RZ°<input id="rot-z" type="number" step="5"></label></div>
    <label class="field-label">Role</label><input id="role-input" class="full-input"><label class="field-label">Parent</label><input id="parent-input" class="full-input" placeholder="object id or empty">
    <div class="coordinate-grid"><label>Amount<input id="amount-input" type="number" min="0.0001" step="0.1"></label><label>Density<input id="density-input" type="number" min="0.0001" step="0.1"></label><label>k_v<input id="kv-input" type="number" min="0.0001" step="0.1"></label></div>
    <label class="field-label">Initial linear velocity</label><div class="coordinate-grid"><label>VX<input id="vel-x" type="number" step="0.01"></label><label>VY<input id="vel-y" type="number" step="0.01"></label><label>VZ<input id="vel-z" type="number" step="0.01"></label></div>
    <label class="field-label">Initial angular velocity</label><div class="coordinate-grid"><label>ωX<input id="omega-x" type="number" step="0.01"></label><label>ωY<input id="omega-y" type="number" step="0.01"></label><label>ωZ<input id="omega-z" type="number" step="0.01"></label></div>
    <label class="field-label">Packing</label><div class="split-fields"><select id="packing-mode"><option>SC</option><option>BCC</option><option selected>FCC</option><option>HCP</option><option>IMPORTED_POINTS</option></select><select id="packing-level"><option>P0</option><option>P1</option><option>P2</option><option>P3</option><option>P4</option></select></div>
    <div class="numeric-grid"><label>Display<output id="display-elements">—</output></label><label>Compute<output id="compute-elements">—</output></label><label>Method<output id="evaluation-method">—</output></label><label>State<output id="selected-state">—</output></label></div>
   </section>
  </aside>
  <section class="viewport-column"><div class="viewport-head"><div><p class="eyebrow">INSTANCED 3D SCENE</p><h2 id="viewport-title"></h2></div><div class="legend"><span><i class="dot movable"></i>movable</span><span><i class="dot rigid"></i>locked</span><span><i class="dot control"></i>KOU</span></div></div><div id="viewport" class="viewport" data-testid="viewport"><div class="viewport-overlay top-left">GIZMO · local/world · snap · edit pauses run</div><div class="viewport-overlay bottom-left"><span id="frame-status">STEP 0</span><b id="motion-status">PAUSED</b></div></div></section>
  <aside class="panel right-panel">
   <div class="panel-heading"><div><p class="eyebrow">SIMULATION</p><h2>Independent speed controls</h2></div><span id="run-lamp" class="run-lamp"></span></div>
   <div class="transport"><button id="run-button" class="primary" data-testid="run">Run</button><button id="stop-button" data-testid="stop">Stop</button><button id="step-button" data-testid="step">Step</button><button id="reset-button" data-testid="reset">Reset</button></div>
   <label class="field-label">Speed preset</label><select id="speed-preset"><option value="SLOW">SLOW INSPECTION</option><option value="NORMAL" selected>NORMAL</option><option value="FAST">FAST</option><option value="VERY_FAST">VERY FAST</option><option value="MAX">MAX BENCHMARK</option></select>
   <label class="field-label">Integration dt · 1e-5…5e-2</label><input id="dt" type="number" min="0.00001" max="0.05" step="0.00001">
   <label class="field-label">Substeps per visual frame</label><select id="substeps">${[1,2,4,8,16,32,64,128,256].map(n=>`<option>${n}</option>`).join("")}</select>
   <label class="field-label">Playback · 0.1×…1000×</label><input id="playback" data-testid="playback" type="range" min="-1" max="3" step="0.1"><output id="playback-value"></output>
   <label class="field-label">Render FPS cap</label><select id="fps-cap"><option>15</option><option>30</option><option selected>60</option><option value="0">unlimited</option></select>
   <label class="visibility-toggle"><input id="damping-enabled" type="checkbox"> Preview-only damping OFF</label><input id="damping-factor" type="number" min="0" max="1" step="0.001" value="0.997" disabled>
   <div class="compact-actions"><button id="lock-all">LOCK ALL</button><button id="unlock-all">UNLOCK ALL</button><button id="lock-far">LOCK FAR KOU</button><button id="unlock-near">UNLOCK NEAR</button><button id="freeze-state">FREEZE</button><button id="restore-state">RESTORE</button></div>
   <div class="section-rule"><span>LIVE METRICS</span></div><div class="ledger-grid"><div><span>Steps/s</span><strong id="steps-ps">0</strong></div><div><span>Visual FPS</span><strong id="visual-fps">0</strong></div><div><span>Sim time</span><strong id="sim-time">0</strong></div><div><span>Compute/render</span><strong id="compute-render">0 / 0 ms</strong></div><div><span>Momentum</span><strong id="momentum">0</strong></div><div><span>Centre of amount</span><strong id="centre-amount">0</strong></div><div><span>Angular momentum</span><strong id="angular-momentum">0</strong></div><div><span>Action residual</span><strong id="action-residual">0</strong></div><div><span>Amount residual</span><strong id="amount-residual">0</strong></div><div><span>Instances</span><strong id="visible-instances">0</strong></div></div><p id="webgpu-status" class="claim-note" data-testid="webgpu-status">Frozen CPU/WebGPU parity gate: checking…</p>
   <div class="section-rule"><span>WORKING KOU</span></div><div class="split-fields"><select id="kou-preset"><option>TINY</option><option selected>M0_K4</option><option>M0_K6</option><option>CUSTOM</option></select><button id="regenerate-kou">REGENERATE</button></div>
   <div class="kou-grid"><label>m<input id="kou-m" type="number" min="1" step="1"></label><label>Tiers K<input id="kou-tiers" type="number" min="1" max="12" step="1"></label><label>Spacing<input id="kou-spacing" type="number" min="0.01" step="0.1"></label><label>Body amount<input id="kou-amount" type="number" min="0.0001" step="0.01"></label><label>Body radius<input id="kou-radius" type="number" min="0.001" step="0.01"></label><label>Seed<input id="kou-seed" type="number" step="1"></label><label>Near tiers<input id="kou-near" type="number" min="0" step="1"></label><label>Guard tiers<input id="kou-guard" type="number" min="0" step="1"></label><label>Far tiers<input id="kou-far" type="number" min="0" step="1"></label></div>
   <label class="visibility-toggle"><input id="all-kou-movable" type="checkbox"> ALL KOU MOVABLE diagnostic</label><div class="kou-tier-controls"><label>Tier<input id="kou-tier" type="number" min="1" step="1" value="1"></label><select id="kou-tier-role"><option>ARENA</option><option>MOVABLE_BUFFER</option><option>GUARD_CONTOUR</option><option>FAR_EXTERNAL_CONTOUR</option><option>NUMERICAL_EDGE_DIAGNOSTIC</option></select></div><div class="compact-actions"><button id="select-kou-tier">SELECT TIER</button><button id="hide-kou-tier">HIDE</button><button id="show-kou-tier">SHOW</button><button id="lock-kou-tier">LOCK</button><button id="unlock-kou-tier">UNLOCK</button><button id="apply-kou-role">SET ROLE</button><button id="rotate-kou">ROTATE 15°</button></div><div id="kou-status" class="claim-note">No KOU in scene</div>
   <div id="error-banner" class="error-banner" role="alert" hidden></div>
  </aside>
 </section>
 <section class="diagnostic-panel">
  <div class="diagnostic-card"><p class="eyebrow">FIRST-HIT SKY</p><h3>Geometric external-support gate</h3><div class="compact-actions"><button id="firsthit-run">COMPUTE 16,384</button><button data-mode="SKY_VIEW">SKY</button><button data-mode="SPHERE_VIEW">SPHERE</button><button data-mode="CHRYSANTHEMUM">CHRYSANTHEMUM</button><button data-mode="RAYS">RAYS</button></div><canvas id="sky-map" width="520" height="150" data-testid="sky-map"></canvas><p id="firsthit-status">Not computed.</p><p class="claim-note">CLOSED SKY = geometric external-support gate; not automatically stable equilibrium or Upor validation.</p></div>
  <div class="diagnostic-card" id="angular-card"><p class="eyebrow">V2B3C GOVERNED ANGULAR ROUTES</p><h3>Spherical footprint · sampled hit support · H(Ω)</h3><select id="angular-operator" data-testid="angular-operator"><option selected>GOVERNED_V2B3C_PACKET_PLAYBACK</option><option>POINT_CUBATURE_CONTROL</option><option>P2_FIXED_FIBONACCI_CURVED_ANGULAR</option><option>P3A_ADAPTIVE_CURVED_ANGULAR</option><option>P3B_EXACT_CAP_SPHERE</option><option>P3B_GLOBAL_GAUSS_RAY_INTERVALS</option><option>P3C_EXPLICIT_SPHERICAL_POLYGON_BOOLEAN_FUTURE</option></select><canvas id="angular-map" width="520" height="150" data-testid="angular-map"></canvas><p id="governed-packet-status">Governed packet loading…</p><p id="angular-status"></p><div id="angular-metadata" class="angular-metadata" data-testid="angular-metadata"></div><p id="p2-outlier" class="claim-note"></p><p class="claim-note">Golden verdict: CURVED_SOLID_ANGLE_ANALYTIC_ORACLE_BLOCKER · no browser promotion.</p></div>
  <div class="diagnostic-card action-tally-card"><p class="eyebrow">G4 GOVERNED ACTION TALLY</p><h3>Resolved − homogenized receiver readout</h3><div class="action-tally-controls"><select id="action-tally-branch" data-testid="action-tally-branch"><option>H0_HOMOGENIZED</option><option>R0_FORWARD_PRESERVING</option><option>R1_ISOTROPIC_REDIRECTION</option><option selected>R2_SPECULAR_REDIRECTION</option><option>R3_SOURCE_COMPATIBLE_CANDIDATE</option></select><select id="action-tally-body" data-testid="action-tally-body"><option value="receiver">receiver</option><option value="structure">structure</option></select></div><canvas id="action-tally-map" width="520" height="180" data-testid="action-tally-map"></canvas><p id="action-tally-packet-status">Governed ActionTally packet loading…</p><p id="action-tally-status"></p><div id="action-tally-metadata" class="angular-metadata" data-testid="action-tally-metadata"></div><p class="claim-note action-tally-firewall">PATH DEPTH = geometry/topology only · cell action already contains ΔΩ · physical force unavailable until cadence is bound.</p></div>
 </section>
 <section class="matched-residual-section"><div class="panel-heading"><div><p class="eyebrow">GOVERNED MR / DL PLAYBACK</p><h2>Matched residual diagnostic catalogue</h2></div><span class="count-pill">16 packet cases</span></div><p class="matched-intro">MR00–MR07 use the current G4 ActionTally replay. DL00–DL07 preserve the available legacy matched-residual diagnostics and are not presented as editable 3D scenes or physical-force results.</p><div class="matched-residual-grid"><div class="matched-focus"><div class="matched-case-controls"><label>Case<select id="matched-case" data-testid="matched-case"><option>MR00</option><option>MR01</option><option selected>MR02</option><option>MR03</option><option>MR04</option><option>MR05</option><option>MR06</option><option>MR07</option><option>DL00</option><option>DL01</option><option>DL02</option><option>DL03</option><option>DL04</option><option>DL05</option><option>DL06</option><option>DL07</option></select></label></div><canvas id="matched-residual-map" width="700" height="150" data-testid="matched-residual-map"></canvas><p id="matched-packet-status">Governed MR/DL packet loading…</p><p id="matched-case-status"></p><div id="matched-case-metadata" class="angular-metadata" data-testid="matched-case-metadata"></div><p class="claim-note action-tally-firewall">MR standard-null and current ActionTally delta are distinct quantities. DL playback retains only the available legacy diagnostic result. No physical-force conversion is performed.</p></div><div class="catalogue-wrap matched-catalogue-wrap"><table id="matched-case-table" data-testid="matched-case-table"><thead><tr><th>Case</th><th>Definition</th><th>Lane</th><th>Standard null</th><th>Current tally norm</th><th>Status</th></tr></thead><tbody></tbody></table></div></div></section>
 <section class="catalogue-section"><div class="panel-heading"><div><p class="eyebrow">COMPLETE PREREGISTERED SUITE</p><h2>Scene catalogue</h2></div><span class="count-pill">17 scenes</span></div><div class="catalogue-wrap"><table id="scene-catalogue" data-testid="scene-catalogue"><thead><tr><th>Scene</th><th>Category</th><th>Mobility</th><th>KOU</th><th>Packing</th><th>First hit</th><th>Status</th><th>Claim ceiling</th></tr></thead><tbody></tbody></table></div></section>
 <section class="bottom-panel"><div class="bottom-card"><p class="eyebrow">SCENE EXCHANGE V2</p><div class="file-actions"><label class="file-button">IMPORT JSON<input id="scene-file" type="file" accept=".json" data-testid="scene-file"></label><button id="export-scene" data-testid="export-scene">EXPORT V2</button><button id="load-max-fixture">LOAD 3DS MAX FIXTURE</button></div><p id="file-status" class="muted">v1 migration and v2 round-trip supported.</p></div><div class="bottom-card"><p class="eyebrow">AUTHORITY SPLIT</p><span class="status-chip preview">PREVIEW</span><p>Editable browser-local calculation.</p><span class="status-chip authority">AUTHORITATIVE</span><p>Read-only governed repository packets only.</p></div><div class="bottom-card"><p class="eyebrow">PUBLIC SAFETY</p><strong>NO PRIVATE CORPUS</strong><p>NO UPOR · NO DIPOLE · NO SCALE · NO VALIDATION</p></div></section>
 <footer><span>VoxelLab Scene Lab V2</span><span>symplectic Euler · no hidden damping · explicit compression</span><strong>PUBLIC ENGINEERING PREVIEW</strong></footer>
</main>`;

function el<T extends HTMLElement>(selector: string): T { const result = document.querySelector<T>(selector); if (!result) throw new Error(`Missing ${selector}`); return result; }

export class SceneLabApp {
  private scene = loadSceneV2(defaultSceneV2Id); private initial = structuredClone(this.scene); private selectedId = this.scene.objects[0]!.object_id; private governedPacket: BrowserPacketV2 | null = null; private actionTallyPlayback: ActionTallyPlayback | null = null; private matchedResidualPlayback: MatchedResidualPlayback | null = null;
  private history = new EditHistory(this.scene); private result: ComputeResult | null = null; private firstHit: FirstHitResult | null = null; private running = false; private raf = 0; private lastFrame = 0; private steps = 0; private simulatedTime = 0; private meter = new FrameMeter();
  private readonly viewport: SceneLabViewport;
  constructor(private readonly root: HTMLElement) { root.innerHTML = template; el("#app-commit").textContent = APP_COMMIT.slice(0, 12); this.populateScenes(); this.viewport = new SceneLabViewport(el("#viewport"), id => this.select(id), (id,p,q)=>this.applyViewportTransform(id,p,q), active=>{ if(active) this.stop(); }); this.bind(); this.load(this.scene); void this.loadGovernedV2B3cPacket(); void this.loadActionTallyPacket(); void this.loadMatchedResidualPacket(); void this.checkWebGpuParity();window.setInterval(()=>this.renderViewportPerformance(),500); }
  private bind() {
    el<HTMLSelectElement>("#scene-select").onchange = e => this.load(loadSceneV2((e.target as HTMLSelectElement).value));
    el("#run-button").onclick = () => this.start(); el("#stop-button").onclick = () => this.stop(); el("#step-button").onclick = () => this.stepMany(1); el("#reset-button").onclick = () => this.reset();
    el<HTMLSelectElement>("#speed-preset").onchange = e => this.applyPreset((e.target as HTMLSelectElement).value);
    el<HTMLInputElement>("#dt").onchange = e => { this.scene.simulation.dt = Number((e.target as HTMLInputElement).value); };
    el<HTMLSelectElement>("#substeps").onchange = e => { this.scene.simulation.substeps_per_frame = Number((e.target as HTMLSelectElement).value); };
    el<HTMLInputElement>("#playback").oninput = e => { this.scene.simulation.playback_speed = 10 ** Number((e.target as HTMLInputElement).value); this.syncSpeed(); };
    el<HTMLSelectElement>("#fps-cap").onchange = e => { this.scene.simulation.fps_cap = Number((e.target as HTMLSelectElement).value) as SceneDocumentV2["simulation"]["fps_cap"]; };
    el<HTMLInputElement>("#damping-enabled").onchange = e => { this.scene.simulation.damping_enabled = (e.target as HTMLInputElement).checked; el<HTMLInputElement>("#damping-factor").disabled = !this.scene.simulation.damping_enabled; (e.target as HTMLElement).parentElement!.lastChild!.textContent = this.scene.simulation.damping_enabled ? " Preview-only damping ENABLED" : " Preview-only damping OFF"; };
    el<HTMLInputElement>("#damping-factor").onchange = e => { this.scene.simulation.damping_factor = Number((e.target as HTMLInputElement).value); };
    ["x","y","z"].forEach((axis, index) => el<HTMLInputElement>(`#pos-${axis}`).onchange = e => this.editSelected(body => { body.transform.position[index] = Number((e.target as HTMLInputElement).value); }));
    ["x","y","z"].forEach(() => {}); ["x","y","z"].forEach(() => {});
    ["x","y","z"].forEach((axis) => el<HTMLInputElement>(`#rot-${axis}`).onchange = () => this.editRotation());
    el("#gizmo-translate").onclick = () => this.viewport.setTransformMode("translate"); el("#gizmo-rotate").onclick = () => this.viewport.setTransformMode("rotate");
    el<HTMLSelectElement>("#gizmo-space").onchange = e => this.viewport.setTransformSpace((e.target as HTMLSelectElement).value as "local"|"world");
    el<HTMLInputElement>("#snap-position").onchange = e => this.viewport.setSnaps(Number((e.target as HTMLInputElement).value) || null, 15);
    el("#lock-selected").onclick = () => this.editSelected(b => { b.world_locked = true; b.movable_translation = false; b.movable_rotation = false; });
    el("#unlock-selected").onclick = () => this.editSelected(b => { b.world_locked = false; b.movable_translation = true; b.movable_rotation = true; });
    el("#lock-all").onclick = () => this.editScene(s => s.objects.forEach(b => { b.world_locked = true; b.movable_translation = false; b.movable_rotation = false; }));
    el("#unlock-all").onclick = () => this.editScene(s => s.objects.forEach(b => { b.world_locked = false; b.movable_translation = true; b.movable_rotation = true; }));
    el("#lock-far").onclick = () => this.editScene(s => s.objects.filter(b=>b.kou_role === "FAR_EXTERNAL_CONTOUR").forEach(b=>{b.world_locked=true;b.movable_translation=false;}));
    el("#unlock-near").onclick = () => this.editScene(s => s.objects.filter(b=>b.kou_role === "MOVABLE_BUFFER").forEach(b=>{b.world_locked=false;b.movable_translation=true;}));
    el("#freeze-state").onclick = () => { this.initial = structuredClone(this.scene); this.notice("Current state frozen as restore point."); };
    el("#restore-state").onclick = () => this.load(structuredClone(this.initial));
    el("#undo").onclick = () => { this.scene = this.history.undo(); this.refresh(true); }; el("#redo").onclick = () => { this.scene = this.history.redo(); this.refresh(true); };
    el("#add-body").onclick = () => this.addBody(); el("#duplicate-body").onclick = () => this.duplicate(); el("#delete-body").onclick = () => this.remove();
    el("#group-body").onclick = () => this.editSelected(b => { b.group_id = `group-${Date.now().toString(36)}`; }); el("#ungroup-body").onclick = () => this.editSelected(b => { b.group_id = "ungrouped"; b.parent_id = null; });
    el<HTMLInputElement>("#role-input").onchange = e => this.editSelected(b => { b.body_role = (e.target as HTMLInputElement).value; }); el<HTMLInputElement>("#parent-input").onchange = e => this.editSelected(b => { b.parent_id = (e.target as HTMLInputElement).value || null; });
    [["amount-input","amount"],["density-input","density"],["kv-input","k_v"]].forEach(([id,key]) => el<HTMLInputElement>(`#${id}`).onchange = e => this.editSelected(b => { (b as unknown as Record<string, number>)[key!] = Number((e.target as HTMLInputElement).value); if(key === "amount") this.regeneratePacking(b); }));
    ["x","y","z"].forEach((axis,index)=>el<HTMLInputElement>(`#vel-${axis}`).onchange=e=>this.editSelected(b=>{b.initial_velocity[index]=Number((e.target as HTMLInputElement).value);b.velocity[index]=b.initial_velocity[index]!;}));
    ["x","y","z"].forEach((axis,index)=>el<HTMLInputElement>(`#omega-${axis}`).onchange=e=>this.editSelected(b=>{b.initial_angular_velocity[index]=Number((e.target as HTMLInputElement).value);b.angular_velocity[index]=b.initial_angular_velocity[index]!;}));
    el<HTMLSelectElement>("#packing-mode").onchange = () => this.changePacking(); el<HTMLSelectElement>("#packing-level").onchange = () => this.changePacking();
    el("#regenerate-kou").onclick = () => this.regenerateKou(); el<HTMLInputElement>("#all-kou-movable").onchange = e => this.editScene(s => { if(s.kou) s.kou.all_movable=(e.target as HTMLInputElement).checked; s.objects.filter(b=>b.kou_tier).forEach(b=>{b.world_locked=!(e.target as HTMLInputElement).checked && b.kou_role === "FAR_EXTERNAL_CONTOUR"; b.movable_translation=!b.world_locked;b.movable_rotation=!b.world_locked;}); });
    el("#select-kou-tier").onclick=()=>this.selectKouTier();el("#hide-kou-tier").onclick=()=>this.editKouTier(b=>{b.visible=false;},true);el("#show-kou-tier").onclick=()=>this.editKouTier(b=>{b.visible=true;},false);el("#lock-kou-tier").onclick=()=>this.editKouTier(b=>{b.world_locked=true;b.movable_translation=false;b.movable_rotation=false;});el("#unlock-kou-tier").onclick=()=>this.editKouTier(b=>{b.world_locked=false;b.movable_translation=true;b.movable_rotation=true;});el("#apply-kou-role").onclick=()=>this.editKouTier(b=>{b.kou_role=el<HTMLSelectElement>("#kou-tier-role").value as RigidGroup["kou_role"];b.body_role=b.kou_role!;});el("#rotate-kou").onclick=()=>this.rotateKou();
    el("#firsthit-run").onclick = () => this.computeFirstHit(); document.querySelectorAll<HTMLButtonElement>("[data-mode]").forEach(button => button.onclick=()=>{this.scene.first_hit.mode=button.dataset.mode as SceneDocumentV2["first_hit"]["mode"]; this.viewport.showFirstHit(this.firstHit);});
    el<HTMLCanvasElement>("#sky-map").onclick=event=>this.probeFirstHit(event);
    el<HTMLSelectElement>("#angular-operator").onchange = e => this.renderAngular((e.target as HTMLSelectElement).value as AngularOperator);
    el<HTMLSelectElement>("#action-tally-branch").onchange = () => this.renderActionTally(); el<HTMLSelectElement>("#action-tally-body").onchange = () => this.renderActionTally();
    el<HTMLSelectElement>("#matched-case").onchange = () => this.renderMatchedResidual();
    el<HTMLInputElement>("#scene-file").onchange = e => void this.importScene(e); el("#export-scene").onclick = () => this.exportScene(); el("#load-max-fixture").onclick = () => void this.loadMaxFixture();
  }
  private populateScenes() { const select = el<HTMLSelectElement>("#scene-select"), body = el<HTMLTableSectionElement>("#scene-catalogue tbody"); for(const item of sceneCatalogue){ select.add(new Option(`${item.scene_id} — ${item.display_name}`, item.scene_id)); const row=document.createElement("tr"); row.innerHTML=`<td><button data-launch="${item.scene_id}">${item.scene_id} · ${item.display_name}</button></td><td>${item.category}</td><td>${item.mobility}</td><td>${item.kou}</td><td>${item.packing}</td><td>${item.first_hit}</td><td>${item.last_run_status}</td><td>${item.claim_ceiling}</td>`; body.append(row); } body.querySelectorAll<HTMLButtonElement>("[data-launch]").forEach(b=>b.onclick=()=>this.load(loadSceneV2(b.dataset.launch!))); }
  private load(scene: SceneDocumentV2) { this.stop(); this.scene=parseSceneV2(scene); this.initial=structuredClone(this.scene); this.selectedId=this.scene.objects[0]!.object_id; this.history.replace(this.scene); this.steps=0; this.simulatedTime=0; this.firstHit=null;this.viewport.showFirstHit(null);this.meter.reset(); this.refresh(true); this.renderAngular("GOVERNED_V2B3C_PACKET_PLAYBACK"); }
  private refresh(rebuild=false){ el<HTMLSelectElement>("#scene-select").value=this.scene.scene_id; el("#scene-description").textContent=this.scene.description; el("#mobility-summary").textContent=`Mobility: ${this.scene.mobility_summary}. Locked roles are explicit.`; el("#viewport-title").textContent=this.scene.display_name; el("#object-count").textContent=`${this.scene.objects.length} bodies`; if(rebuild)this.viewport.setScene(this.scene); else this.viewport.syncTransforms(this.scene); this.renderTree(); this.renderInspector(); this.syncSpeed(); this.syncKouControls(); this.renderMetrics(); }
  private renderTree(){const holder=el("#scene-tree");holder.replaceChildren();this.scene.objects.forEach(b=>{const button=document.createElement("button");button.className=`tree-row${b.object_id===this.selectedId?" selected":""}`;button.innerHTML=`<span class="tree-icon ${b.kou_tier?"far":"volume"}"></span><span class="tree-copy"><strong></strong><small></small></span><span class="lock">${b.world_locked?"LOCK":"MOVE"}</span>`;button.querySelector("strong")!.textContent=b.display_name;button.querySelector("small")!.textContent=`${b.body_role} · ${b.group_id}`;button.onclick=()=>this.select(b.object_id);holder.append(button);});}
  private select(id:string){this.selectedId=id;this.viewport.setSelected(id);this.renderTree();this.renderInspector();}
  private selected(){return this.scene.objects.find(b=>b.object_id===this.selectedId)!;}
  private renderInspector(){
    const b=this.selected();if(!b)return;
    el("#selected-name").textContent=b.display_name;
    ["x","y","z"].forEach((axis,index)=>{el<HTMLInputElement>(`#pos-${axis}`).value=String(b.transform.position[index]);el<HTMLInputElement>(`#vel-${axis}`).value=String(b.initial_velocity[index]);el<HTMLInputElement>(`#omega-${axis}`).value=String(b.initial_angular_velocity[index]);});
    const e=new THREE.Euler().setFromQuaternion(new THREE.Quaternion(...b.transform.rotation));[e.x,e.y,e.z].forEach((v,i)=>el<HTMLInputElement>(`#rot-${"xyz"[i]}`).value=(v*180/Math.PI).toFixed(2));
    el<HTMLInputElement>("#role-input").value=b.body_role;el<HTMLInputElement>("#parent-input").value=b.parent_id??"";el<HTMLInputElement>("#amount-input").value=String(b.amount);el<HTMLInputElement>("#density-input").value=String(b.density);el<HTMLInputElement>("#kv-input").value=String(b.k_v);el<HTMLSelectElement>("#packing-mode").value=b.packing.mode;el<HTMLSelectElement>("#packing-level").value=b.packing.level;
    el("#display-elements").textContent=String(b.packing.display_count);el("#compute-elements").textContent=String(b.packing.compute_count);const pointOperator=b.representation_mode==="CM_CONTROL"?"CM_CONTROL":`POINT_CUBATURE_${b.packing.mode.replace("IMPORTED_POINTS","IMPORTED")}`;el("#evaluation-method").textContent=`BODY=RIGID_GROUP · OPERATOR=${pointOperator} · ACCELERATOR=${this.scene.simulation.evaluation_method}`;el("#selected-state").textContent=b.world_locked?"WORLD LOCKED":"MOVABLE";
    const counts=this.scene.objects.filter(x=>x.kou_tier).reduce<Record<number,number>>((a,x)=>{a[x.kou_tier!]=(a[x.kou_tier!]??0)+1;return a;},{});el("#kou-status").textContent=this.scene.kou?`${this.scene.kou.preset}: ${Object.entries(counts).map(([k,n])=>`tier ${k}=${n}`).join(", ")}`:"No KOU in scene";
  }
  private editScene(change:(s:SceneDocumentV2)=>void){this.stop();const next=structuredClone(this.scene);change(next);this.scene=this.history.push(next);this.refresh(true);}
  private editSelected(change:(b:RigidGroup)=>void){this.editScene(s=>{const b=s.objects.find(x=>x.object_id===this.selectedId);if(b)change(b);});}
  private editRotation(){const e=new THREE.Euler(...(["x","y","z"].map(a=>Number(el<HTMLInputElement>(`#rot-${a}`).value)*Math.PI/180) as Vec3));const q=new THREE.Quaternion().setFromEuler(e).toArray() as Quat;this.editSelected(b=>{b.transform.rotation=q;});}
  private applyViewportTransform(id:string,p:Vec3,q:Quat){const b=this.scene.objects.find(x=>x.object_id===id);if(!b)return;b.transform.position=[...p];b.transform.rotation=[...q];this.renderInspector();}
  private regeneratePacking(b:RigidGroup){if(b.packing.mode==="IMPORTED_POINTS")return;const generated=generatePacking(b.packing.mode,b.packing.level,b.outer_radius,b.amount,b.packing.custom_count);b.packing=generated.definition;b.voxel_elements=generated.elements;}
  private changePacking(){this.editSelected(b=>{b.packing.mode=el<HTMLSelectElement>("#packing-mode").value as PackingMode;b.packing.level=el<HTMLSelectElement>("#packing-level").value as PackingLevel;this.regeneratePacking(b);});}
  private addBody(){const base=loadSceneV2("S02").objects[0]!;base.object_id=`body-${Date.now().toString(36)}`;base.display_name="New positive body";base.transform.position=[0,1,0];this.editScene(s=>s.objects.push(base));this.selectedId=base.object_id;}
  private duplicate(){const clone=structuredClone(this.selected());clone.object_id=`${clone.object_id}-copy-${Date.now().toString(36)}`;clone.display_name+= " copy";clone.transform.position[0]+=.6;this.editScene(s=>s.objects.push(clone));this.selectedId=clone.object_id;}
  private remove(){if(this.scene.objects.length<=1)return;this.editScene(s=>{s.objects=s.objects.filter(b=>b.object_id!==this.selectedId);});this.selectedId=this.scene.objects[0]!.object_id;this.refresh(true);}
  private regenerateKou(){const preset=el<HTMLSelectElement>("#kou-preset").value as "TINY"|"M0_K4"|"M0_K6"|"CUSTOM";this.editScene(s=>{const old=s.kou??loadSceneV2("S05").kou!;const declared=preset==="TINY"?{m:1,tiers:3}:preset==="M0_K4"?{m:3,tiers:4}:preset==="M0_K6"?{m:3,tiers:6}:{m:Math.max(1,Math.round(Number(el<HTMLInputElement>("#kou-m").value))),tiers:Math.max(1,Math.round(Number(el<HTMLInputElement>("#kou-tiers").value)))};const config={...old,preset,...declared,tier_spacing:Number(el<HTMLInputElement>("#kou-spacing").value),body_amount:Number(el<HTMLInputElement>("#kou-amount").value),body_radius:Number(el<HTMLInputElement>("#kou-radius").value),orientation_seed:Math.round(Number(el<HTMLInputElement>("#kou-seed").value)),near_movable_tiers:Math.max(0,Math.round(Number(el<HTMLInputElement>("#kou-near").value))),guard_tiers:Math.max(0,Math.round(Number(el<HTMLInputElement>("#kou-guard").value))),far_fixed_tiers:Math.max(0,Math.round(Number(el<HTMLInputElement>("#kou-far").value)))};s.kou=config;s.objects=s.objects.filter(b=>!b.kou_tier).concat(generateKou(config));});}
  private syncKouControls(){const config=this.scene.kou??loadSceneV2("S05").kou!;el<HTMLSelectElement>("#kou-preset").value=config.preset;const values:Record<string,number>={"kou-m":config.m,"kou-tiers":config.tiers,"kou-spacing":config.tier_spacing,"kou-amount":config.body_amount,"kou-radius":config.body_radius,"kou-seed":config.orientation_seed,"kou-near":config.near_movable_tiers,"kou-guard":config.guard_tiers,"kou-far":config.far_fixed_tiers};Object.entries(values).forEach(([id,value])=>{el<HTMLInputElement>(`#${id}`).value=String(value);});el<HTMLInputElement>("#all-kou-movable").checked=config.all_movable;el<HTMLInputElement>("#kou-tier").max=String(config.tiers);}
  private selectedKouTier(){return Math.max(1,Math.round(Number(el<HTMLInputElement>("#kou-tier").value)||1));}
  private selectKouTier(){const body=this.scene.objects.find(candidate=>candidate.kou_tier===this.selectedKouTier());if(body)this.select(body.object_id);else this.notice("Selected scene has no body on that KOU tier.");}
  private editKouTier(change:(body:RigidGroup)=>void,hidden?:boolean){const tier=this.selectedKouTier();this.editScene(s=>{s.objects.filter(body=>body.kou_tier===tier).forEach(change);if(s.kou&&hidden!==undefined)s.kou.hidden_tiers=hidden?[...new Set([...s.kou.hidden_tiers,tier])]:s.kou.hidden_tiers.filter(value=>value!==tier);});}
  private rotateKou(){const angle=Math.PI/12,c=Math.cos(angle),s=Math.sin(angle),q=new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0,1,0),angle);this.editScene(scene=>scene.objects.filter(body=>body.kou_tier).forEach(body=>{const [x,y,z]=body.transform.position;body.transform.position=[c*x+s*z,y,-s*x+c*z];body.transform.rotation=q.clone().multiply(new THREE.Quaternion(...body.transform.rotation)).toArray() as Quat;}));}
  private applyPreset(name:string){const settings={SLOW:[.0002,1,.1,30],NORMAL:[.002,4,1,60],FAST:[.002,16,10,60],VERY_FAST:[.001,64,100,60],MAX:[.0005,256,1000,0]}[name]??[.002,4,1,60];[this.scene.simulation.dt,this.scene.simulation.substeps_per_frame,this.scene.simulation.playback_speed,this.scene.simulation.fps_cap]=settings as [number,number,number,0|15|30|60];this.syncSpeed();}
  private syncSpeed(){el<HTMLInputElement>("#dt").value=String(this.scene.simulation.dt);el<HTMLSelectElement>("#substeps").value=String(this.scene.simulation.substeps_per_frame);el<HTMLInputElement>("#playback").value=String(Math.log10(this.scene.simulation.playback_speed));el("#playback-value").textContent=`${fmt(this.scene.simulation.playback_speed)}×`;el<HTMLSelectElement>("#fps-cap").value=String(this.scene.simulation.fps_cap);}
  private stepMany(count:number){let compute=0;for(let i=0;i<count;i++){this.result=symplecticStep(this.scene);compute+=this.result.compute_ms;this.steps++;this.simulatedTime+=this.scene.simulation.dt;}this.viewport.syncTransforms(this.scene);if(this.result)this.viewport.updateResults(this.result);this.meter.record(count,compute,this.viewport.stats().render_ms);this.renderMetrics();}
  private start(){if(this.running||this.scene.scene_class==="SETUP_ONLY")return;this.running=true;this.lastFrame=0;this.meter.reset();const loop=(now:number)=>{if(!this.running)return;const cap=this.scene.simulation.fps_cap;if(cap&&this.lastFrame&&now-this.lastFrame<1000/cap){this.raf=requestAnimationFrame(loop);return;}this.lastFrame=now;const requested=Math.max(1,Math.round(this.scene.simulation.substeps_per_frame*Math.min(16,this.scene.simulation.playback_speed)));const started=performance.now();let done=0;while(done<requested&&performance.now()-started<12){symplecticStep(this.scene);done++;this.steps++;this.simulatedTime+=this.scene.simulation.dt;}this.result=computeBodyPairs(this.scene);this.viewport.syncTransforms(this.scene);this.meter.record(done,this.result.compute_ms,this.viewport.stats().render_ms);this.renderMetrics();this.raf=requestAnimationFrame(loop);};this.renderRun();this.raf=requestAnimationFrame(loop);}
  private stop(){this.running=false;cancelAnimationFrame(this.raf);this.renderRun();}
  private renderRun(){el("#motion-status").textContent=this.running?"RUNNING":"PAUSED";el("#motion-status").classList.toggle("active",this.running);el("#run-lamp").classList.toggle("active",this.running);}
  private reset(){this.load(structuredClone(this.initial));}
  private renderMetrics(){const s=this.meter.snapshot(),l=motionLedgers(this.scene.objects),v=this.viewport.stats();el("#steps-ps").textContent=fmt(s.steps_per_second);el("#visual-fps").textContent=fmt(v.fps);el("#sim-time").textContent=fmt(this.simulatedTime);el("#compute-render").textContent=`${fmt(s.mean_compute_ms)} / ${fmt(v.render_ms)} ms`;el("#momentum").textContent=fmt(Math.hypot(...l.momentum));el("#centre-amount").textContent=l.centre_of_amount.map(fmt).join(" / ");el("#angular-momentum").textContent=fmt(Math.hypot(...l.angular_momentum));el("#action-residual").textContent=fmt(this.result?.action_reaction_residual??0);el("#amount-residual").textContent=fmt(this.result?.amount_residual??0);el("#visible-instances").textContent=String(v.visible_instances);el("#frame-status").textContent=`STEP ${this.steps}`;const selected=this.selected();if(selected)el("#viewport").dataset.selectedPosition=selected.transform.position.join(",");}
  private renderViewportPerformance(){const v=this.viewport.stats();el("#visual-fps").textContent=fmt(v.fps);el("#visible-instances").textContent=String(v.visible_instances);}
  private computeFirstHit(){const observer=this.scene.objects.find(b=>b.object_id===this.scene.first_hit.observer_body_id)??this.selected(),sources=this.scene.objects.filter(b=>b.object_id!==observer.object_id),counts=[192,768,3072,this.scene.first_hit.direction_count].filter((value,index,array)=>array.indexOf(value)===index).sort((a,b)=>a-b),convergence=counts.map(count=>computeFirstHit(observer.transform.position,sources,count,this.scene.first_hit.max_distance));this.firstHit=convergence.at(-1)!;this.viewport.showFirstHit(this.firstHit);this.drawSky();el("#firsthit-status").textContent=`coverage convergence ${convergence.map((result,index)=>`${counts[index]}:${fmt(result.coverage_fraction)}`).join(" · ")} · uncovered Ω=${fmt(this.firstHit.uncovered_solid_angle)} · largest sampled hole=${fmt(this.firstHit.largest_angular_hole)} rad · max hit=${fmt(this.firstHit.maximum_first_hit_distance??NaN)} · click map to inspect first-hit ID/distance`;}
  private drawSky(){if(!this.firstHit)return;const canvas=el<HTMLCanvasElement>("#sky-map"),ctx=canvas.getContext("2d")!;ctx.fillStyle="#06100e";ctx.fillRect(0,0,canvas.width,canvas.height);this.firstHit.directions.forEach((d,i)=>{const x=(Math.atan2(d[2],d[0])/Math.PI/2+.5)*canvas.width,y=(.5-Math.asin(d[1])/Math.PI)*canvas.height;ctx.fillStyle=this.firstHit!.body_ids[i]?"#76f6c2":"#ff805c";ctx.fillRect(x,y,1.5,1.5);});}
  private probeFirstHit(event:MouseEvent){if(!this.firstHit)return;const canvas=el<HTMLCanvasElement>("#sky-map"),rect=canvas.getBoundingClientRect(),x=(event.clientX-rect.left)/rect.width*canvas.width,y=(event.clientY-rect.top)/rect.height*canvas.height;let best=0,bestD=Infinity;this.firstHit.directions.forEach((direction,index)=>{const px=(Math.atan2(direction[2],direction[0])/Math.PI/2+.5)*canvas.width,py=(.5-Math.asin(direction[1])/Math.PI)*canvas.height,dx=Math.min(Math.abs(px-x),canvas.width-Math.abs(px-x)),d=dx*dx+(py-y)**2;if(d<bestD){bestD=d;best=index;}});const body=this.firstHit.body_ids[best]??"OPEN_DIRECTION",distance=this.firstHit.distances[best]!;el("#firsthit-status").textContent+=` · probe index=${best} body=${body} distance=${Number.isFinite(distance)?fmt(distance):"NO_HIT"}`;}
  private renderAngular(operator:AngularOperator){const canvas=el<HTMLCanvasElement>("#angular-map"),ctx=canvas.getContext("2d")!;ctx.fillStyle="#06100e";ctx.fillRect(0,0,canvas.width,canvas.height);const result=operator==="P2_FIXED_FIBONACCI_CURVED_ANGULAR"?fixedFibonacciCurvedAngular([2.5,0,0],[0,0,0],1,1,3072):operator==="P3B_EXACT_CAP_SPHERE"?exactCapPolarGaussSphere([2.5,0,0],[0,0,0],1,1,96):governedPlayback(operator);if(result.directions.length){result.directions.forEach((d,i)=>{const x=(Math.atan2(d[2],d[0])/Math.PI/2+.5)*canvas.width,y=(.5-Math.asin(d[1])/Math.PI)*canvas.height,h=result.h_omega[i]!;ctx.fillStyle=result.hit_mask[i]?`rgb(${Math.min(255,80+h*100)},${Math.min(255,130+h*100)},220)`:"#17302a";ctx.fillRect(x,y,2,2);});}else{ctx.fillStyle=result.authority==="FUTURE_NOT_IMPLEMENTED"?"#ff805c":"#d99cff";ctx.font="12px monospace";ctx.fillText(result.authority==="FUTURE_NOT_IMPLEMENTED"?"P3C future route · NOT IMPLEMENTED":"Governed V2B3C playback · browser recomputation disabled",20,75);}const p2=V2B3C_GOLDEN.p2_outlier_localization;el("#angular-status").textContent=`${V2B3C_GOLDEN.verdict} · ${result.operator} · Ω=${fmt(result.cap_area)} · sampled hits=${result.hit_mask.filter(Boolean).length} · H(Ω) max=${fmt(result.h_omega.length?Math.max(...result.h_omega):0)}`;el("#angular-metadata").innerHTML=`<dl><dt>Body identity</dt><dd>RIGID_GROUP</dd><dt>Operator</dt><dd>${result.operator}</dd><dt>Quadrature</dt><dd>${result.quadrature_family}</dd><dt>Geometry interval</dt><dd>${result.geometry_route}</dd><dt>Directions / samples</dt><dd>${result.direction_count||"governed source count"}</dd><dt>Absolute error</dt><dd>${operator==="GOVERNED_V2B3C_PACKET_PLAYBACK"?"see frozen packet":"NOT ISSUED"}</dd><dt>Relative error</dt><dd>${operator==="GOVERNED_V2B3C_PACKET_PLAYBACK"?"see frozen packet":"NOT ISSUED"}</dd><dt>Reference denominator</dt><dd>${operator==="GOVERNED_V2B3C_PACKET_PLAYBACK"?"source-defined":"NOT PROVIDED"}</dd><dt>Near-zero warning</dt><dd>${operator==="GOVERNED_V2B3C_PACKET_PLAYBACK"?"source-dependent":"NOT LOCALIZED"}</dd><dt>Golden parity</dt><dd>${result.golden_parity}</dd><dt>Authority class</dt><dd>${result.authority}</dd></dl>`;el("#p2-outlier").textContent=`P2 worst-case relative outlier ${V2B3C_GOLDEN.p2_worst_case_relative_outlier}; scene=${p2.scene??"NOT PROVIDED"}, component=${p2.component??"NOT PROVIDED"}, denominator=${p2.relative_denominator??"NOT PROVIDED"}. Cause is not localized; this is not a general 99.8% error claim.`;}
  private renderActionTally(){
    if(!this.actionTallyPlayback)return;
    const branchId=el<HTMLSelectElement>("#action-tally-branch").value as ActionTallyBranchId,body=el<HTMLSelectElement>("#action-tally-body").value as ActionTallyBodyId,branch=this.actionTallyPlayback.branches[branchId],vectors=actionTallyVectors(branch,body),canvas=el<HTMLCanvasElement>("#action-tally-map"),ctx=canvas.getContext("2d")!;
    const rows:[string,Vec3][]=[["resultant",vectors.resultant],["Δ resultant",vectors.resultant_delta],["torque",vectors.torque],["Δ torque",vectors.torque_delta]],components=["#76f6c2","#d99cff","#ffb46d"],maximum=Math.max(1e-15,...rows.flatMap(([,vector])=>vector.map(Math.abs))),origin=300,extent=190;
    ctx.fillStyle="#06100e";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle="#25443c";ctx.beginPath();ctx.moveTo(origin,12);ctx.lineTo(origin,160);ctx.stroke();ctx.font="10px monospace";ctx.textBaseline="middle";
    rows.forEach(([label,vector],row)=>{const y=27+row*36;ctx.fillStyle="#91a9a0";ctx.fillText(label,8,y);vector.forEach((value,axis)=>{const lane=y+(axis-1)*7,end=origin+value/maximum*extent;ctx.strokeStyle=components[axis]!;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(origin,lane);ctx.lineTo(end,lane);ctx.stroke();ctx.fillStyle=components[axis]!;ctx.beginPath();ctx.arc(end,lane,2.5,0,Math.PI*2);ctx.fill();});ctx.fillStyle="#d8ebe4";ctx.fillText(`|·|=${fmt(vectorNorm(vector))}`,92,y);});
    ctx.fillStyle="#718b82";ctx.fillText(`symmetric scale ±${fmt(maximum)} · x/y/z = mint/violet/amber`,8,171);
    const diagnostics=this.actionTallyPlayback.packet.diagnostics,formatVector=(vector:Vec3)=>`[${vector.map(fmt).join(", ")}]`;
    el("#action-tally-status").textContent=`${branchId} · ${body} · events=${branch.event_count} · M0 residual=${fmt(branch.m0_residual)} · deficit-route residual=${fmt(branch.deficit_route_residual)}`;
    el("#action-tally-metadata").innerHTML=`<dl><dt>Resultant action</dt><dd>${formatVector(vectors.resultant)}</dd><dt>Resolved − H0</dt><dd>${formatVector(vectors.resultant_delta)}</dd><dt>Torque action</dt><dd>${formatVector(vectors.torque)}</dd><dt>Torque delta</dt><dd>${formatVector(vectors.torque_delta)}</dd><dt>Incident M0</dt><dd>${fmt(branch.incident_m0)}</dd><dt>Package hash</dt><dd>${branch.package_hash}</dd><dt>Incident packet</dt><dd>${String(diagnostics.incident_packet_hash)}</dd><dt>Weighting</dt><dd>${String(diagnostics.weighting_contract)}</dd><dt>Force status</dt><dd>${String(diagnostics.secondary_verdict)}</dd></dl>`;
  }
  private async loadActionTallyPacket(){try{const response=await fetch(`${import.meta.env.BASE_URL}packets/R12_G4_ACTION_TALLY_BROWSER_PLAYBACK_V1.json`);if(!response.ok)throw new Error(`packet HTTP ${response.status}`);const packet=parseBrowserPacketV2(await response.json());this.actionTallyPlayback=parseActionTallyPlayback(packet);el("#action-tally-packet-status").textContent=`${PACKET_AUTHORITY_NOTICE} Producer ${packet.producer_commit}; ${packet.verdict}.`;this.renderActionTally();}catch(error){el("#action-tally-packet-status").textContent=`Governed ActionTally packet blocked: ${String(error)}`;}}
  private renderMatchedResidual(){
    if(!this.matchedResidualPlayback)return;
    const caseId=el<HTMLSelectElement>("#matched-case").value as MatchedResidualCaseId,item=this.matchedResidualPlayback.cases[caseId],canvas=el<HTMLCanvasElement>("#matched-residual-map"),ctx=canvas.getContext("2d")!,rows:[string,Vec3][]=[["resultant residual",item.resultant_residual],["torque residual",item.torque_residual]],components=["#76f6c2","#d99cff","#ffb46d"],maximum=Math.max(1e-15,...rows.flatMap(([,vector])=>vector.map(Math.abs))),origin=400,extent=270;
    ctx.fillStyle="#06100e";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle="#25443c";ctx.beginPath();ctx.moveTo(origin,12);ctx.lineTo(origin,112);ctx.stroke();ctx.font="11px monospace";ctx.textBaseline="middle";
    rows.forEach(([label,vector],row)=>{const y=38+row*48;ctx.fillStyle="#91a9a0";ctx.fillText(label,12,y);vector.forEach((value,axis)=>{const lane=y+(axis-1)*8,end=origin+value/maximum*extent;ctx.strokeStyle=components[axis]!;ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(origin,lane);ctx.lineTo(end,lane);ctx.stroke();ctx.fillStyle=components[axis]!;ctx.beginPath();ctx.arc(end,lane,3,0,Math.PI*2);ctx.fill();});ctx.fillStyle="#d8ebe4";ctx.fillText(`|·|=${fmt(matchedVectorNorm(vector))}`,175,y);});ctx.fillStyle="#718b82";ctx.fillText(`symmetric scale ±${fmt(maximum)} · x/y/z = mint/violet/amber`,12,136);
    const current=item.current_action_tally_replay_available?`current ActionTally norm=${fmt(item.resultant_residual_norm)}`:"current ActionTally replay=NOT AVAILABLE",formatVector=(vector:Vec3)=>`[${vector.map(fmt).join(", ")}]`;
    el("#matched-case-status").textContent=`${caseId} · ${item.classification} · ${item.lane} · ${current}`;
    el("#matched-case-metadata").innerHTML=`<dl><dt>Definition</dt><dd>${item.definition}</dd><dt>Lane</dt><dd>${item.lane}</dd><dt>Standard-null norm</dt><dd>${fmt(item.standard_null_norm)}</dd><dt>Resultant residual</dt><dd>${formatVector(item.resultant_residual)}</dd><dt>Resultant norm</dt><dd>${fmt(item.resultant_residual_norm)}</dd><dt>Torque residual</dt><dd>${formatVector(item.torque_residual)}</dd><dt>Torque norm</dt><dd>${fmt(item.torque_residual_norm)}</dd><dt>Mode</dt><dd>${item.mode}</dd><dt>Same incident packet</dt><dd>${item.same_incident_packet===null?"NOT AVAILABLE IN LEGACY DL RECEIPT":String(item.same_incident_packet)}</dd><dt>Source commit</dt><dd>${item.source_commit}</dd><dt>Physical force</dt><dd>NOT AVAILABLE</dd></dl>`;
    document.querySelectorAll<HTMLTableRowElement>("#matched-case-table tbody tr").forEach(row=>row.classList.toggle("selected",row.dataset.caseId===caseId));
  }
  private populateMatchedResidualTable(){if(!this.matchedResidualPlayback)return;const body=el<HTMLTableSectionElement>("#matched-case-table tbody");body.innerHTML="";for(const caseId of this.matchedResidualPlayback.case_order){const item=this.matchedResidualPlayback.cases[caseId],row=document.createElement("tr"),current=item.current_action_tally_replay_available?fmt(item.resultant_residual_norm):"NOT REPLAYED";row.dataset.caseId=caseId;row.innerHTML=`<td><button data-matched-case="${caseId}">${caseId}</button></td><td>${item.definition}</td><td>${item.lane}</td><td>${fmt(item.standard_null_norm)}</td><td>${current}</td><td>${item.classification}</td>`;body.append(row);}body.querySelectorAll<HTMLButtonElement>("[data-matched-case]").forEach(button=>button.onclick=()=>{el<HTMLSelectElement>("#matched-case").value=button.dataset.matchedCase!;this.renderMatchedResidual();});}
  private async loadMatchedResidualPacket(){try{const response=await fetch(`${import.meta.env.BASE_URL}packets/R12_MR_DL_MATCHED_RESIDUAL_BROWSER_PLAYBACK_V1.json`);if(!response.ok)throw new Error(`packet HTTP ${response.status}`);const packet=parseBrowserPacketV2(await response.json());this.matchedResidualPlayback=parseMatchedResidualPlayback(packet);el("#matched-packet-status").textContent=`${PACKET_AUTHORITY_NOTICE} MR producer ${String(packet.diagnostics.current_g4_source_commit)}; DL source ${String(packet.diagnostics.legacy_source_commit)}; ${String(packet.diagnostics.dl_current_g4_status)}.`;this.populateMatchedResidualTable();this.renderMatchedResidual();}catch(error){el("#matched-packet-status").textContent=`Governed MR/DL packet blocked: ${String(error)}`;}}
  private async loadGovernedV2B3cPacket(){try{const response=await fetch(`${import.meta.env.BASE_URL}packets/R14_V2B3C_BROWSER_GOLDEN_V1.json`);if(!response.ok)throw new Error(`packet HTTP ${response.status}`);this.governedPacket=parseBrowserPacketV2(await response.json());el("#governed-packet-status").textContent=`${PACKET_AUTHORITY_NOTICE} Producer ${this.governedPacket.producer_commit}; ${this.governedPacket.verdict}.`;this.renderAngular(el<HTMLSelectElement>("#angular-operator").value as AngularOperator);}catch(error){el("#governed-packet-status").textContent=`Governed packet blocked: ${String(error)}`;}}
  private async checkWebGpuParity(){const scene=loadBuiltInScene("SCENE_01_CM_CONTROL"),cpu=computeDirect(scene);const {status}=await initializeWebGpu(scene,cpu);const node=el("#webgpu-status");node.textContent=`Frozen V1 CPU/WebGPU parity: ${status.parity} · adapter=${status.adapter} · ${status.detail}. Scene Lab V2 CPU preview remains explicit.`;node.dataset.parity=status.parity;}
  private exportScene(){const blob=new Blob([serializeSceneV2(this.scene)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`${this.scene.scene_id}.voxellab.scene.json`;a.click();URL.revokeObjectURL(url);this.notice(`Exported ${a.download}`);}
  private async importScene(event:Event){const input=event.target as HTMLInputElement,file=input.files?.[0];if(!file)return;try{this.load(parseSceneV2(JSON.parse(await file.text())));this.notice(`Loaded scene ${this.scene.scene_id} from ${file.name}`);}catch(error){this.error(error instanceof SceneValidationError?error.issues.join(" · "):String(error));}finally{input.value="";}}
  private async loadMaxFixture(){try{const response=await fetch(`${import.meta.env.BASE_URL}fixtures/3dsmax/S17_VOXELLAB_MAX_EXPORT_FIXTURE_V1.voxellab.scene.json`);if(!response.ok)throw new Error(`fixture HTTP ${response.status}`);this.load(parseSceneV2(await response.json()));this.notice("Loaded 3ds Max exporter fixture without manual editing.");}catch(error){this.error(String(error));}}
  private notice(message:string){el("#file-status").textContent=message;el<HTMLElement>("#error-banner").hidden=true;}
  private error(message:string){el("#error-banner").textContent=message;el<HTMLElement>("#error-banner").hidden=false;}
}
